### ISSUE TITLE
Segfault when getting access to 'self.__name__' in a class 

### ISSUE THREAD

**Issue by xiaxinmeng** [exaloop/codon#357]
The following code defines a class Foo with a method goo. Inside the method, it attempts to print the \_\_name\_\_ attribute of the object it is called upon. However, the code should raise an AttributeError  instead of a segmentation fault, since the \_\_name\_\_ attribute is not defined for instances of the Foo class. 

test.py
```
class Foo:
    def goo(self):
    	print(self.__name__)

Foo().goo()
```
The actual output of Codon v016.0:
`Segmentation Fault`

The expected output (CPython 3.10.8):
```
Traceback (most recent call last):
  File "/home/xxm/Desktop/Codon/test.py", line 363, in <module>
    Foo().goo()
  File "/home/xxm/Desktop/Codon/test.py", line 361, in goo
    print(self.__name__)
AttributeError: 'Foo' object has no attribute '__name__'. Did you mean: '__ne__'?
```

Reproduce step:
> download the Pre-built binaries for Linux
> Type " codon run --release test.py" in the console.

Environment:
Ubuntu 18.04
Codon v0.16.0
CPython 3.10.8

**Comment by elisbyberi** [comment]
@xiaxinmeng
Did you mean to print class's name?

``` python
class Foo:
    def goo(self):
        print(Foo.__name__)


Foo().goo()  # Foo
```

**Comment by xiaxinmeng** [comment]
@elisbyberi, I apologize for any confusion my previous response may have caused. I completely agree with you that special variables such as \_\_name\_\_ have their intended use. My point was that perhaps it would be beneficial to implement a checker in Codon that could identify and report more appropriate errors in the release mode, such as an IndexError or an AttributeError, instead of a segmentation fault if these attributes are misused.

**Comment by elisbyberi** [comment]
@xiaxinmeng In "release" mode, debugging is disabled and no error messages should be printed. It is recommended that you debug programs in "debug" mode, which is the default mode. 

By default, running `codon run fib.py` executes the program in "debug" mode.

**Comment by inumanag** [comment]
This is bug on our side. Thank you for the report.

**Comment by inumanag** [comment]
Fixed in #604.
