### ISSUE TITLE
Segmentation fault with -release flag

### ISSUE THREAD

**Issue by Miezhiko** [exaloop/codon#432]
on current develop, works fine without -release flag, segfaults with it, even on small examples

--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=NULL} ---
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault (core dumped)

**Comment by arshajii** [comment]
Hi @Miezhiko -- is the case with any code (e.g. even a simple `print('hello world')`)? Can you also please provide more info about your system, OS, etc.?

**Comment by Miezhiko** [comment]
@arshajii linux, need to provide some versions?

fails with -release on any code, even simple print("a")

**Comment by Miezhiko** [comment]
still reproducable :(

**Comment by inumanag** [comment]
Hi @Miezhiko 

Does the segfault happen with #604 by any chance? What happens if you compile Codon w/ `-DCMAKE_BUILD_TYPE=DEBUG`? If it still crashes, can you please check it in `gdb` or `lldb` to see where it crashes?

**Comment by inumanag** [comment]
Closing due to inactivity; please reopen if still present in v0.19+.

**Comment by Miezhiko** [comment]
will do retest

**Comment by Miezhiko** [comment]
I've updated the ebuild on here https://github.com/Miezhiko/Overlay/blob/mawa/dev-lang/codon/codon-9999.ebuild

still same error with `--release` flag

```
readlink("/data2/contrib/rust/Rarity/simple.py", 0x7ffdf07bbdf0, 1023) = -1 EINVAL (Invalid argument)
brk(0x55fea060e000)                     = 0x55fea060e000
brk(0x55fea062f000)                     = 0x55fea062f000
brk(0x55fea0650000)                     = 0x55fea0650000
brk(0x55fea0671000)                     = 0x55fea0671000
brk(0x55fea0692000)                     = 0x55fea0692000
brk(0x55fea06b3000)                     = 0x55fea06b3000
brk(0x55fea06d4000)                     = 0x55fea06d4000
brk(0x55fea06f5000)                     = 0x55fea06f5000
brk(0x55fea0716000)                     = 0x55fea0716000
brk(0x55fea0739000)                     = 0x55fea0739000
brk(0x55fea075c000)                     = 0x55fea075c000
brk(0x55fea077d000)                     = 0x55fea077d000
brk(0x55fea079e000)                     = 0x55fea079e000
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=NULL} ---
+++ killed by SIGSEGV +++
zsh: segmentation fault  strace codon run --release simple.py
```

**Comment by Miezhiko** [comment]
may try compiling with DEBUG some later

**Comment by Miezhiko** [comment]
@inumanag stacktrace with DEBUG build

```
Thread 1 "codon" received signal SIGSEGV, Segmentation fault.
0x00007ffff40bb300 in codon::ir::analyze::dataflow::RDInspector::analyze() () from /usr/bin/../lib/codon/libcodonc.so
(gdb) bt
#0  0x00007ffff40bb300 in codon::ir::analyze::dataflow::RDInspector::analyze() () from /usr/bin/../lib/codon/libcodonc.so
#1  0x00007ffff40bc684 in codon::ir::analyze::dataflow::RDAnalysis::run(codon::ir::Module const*) () from /usr/bin/../lib/codon/libcodonc.so
#2  0x00007ffff4153c8a in codon::ir::transform::PassManager::runAnalysis(codon::ir::Module*, std::__cxx11::basic_string<char, std::char_traits<char>, std::all
ocator<char> > const&) () from /usr/bin/../lib/codon/libcodonc.so
#3  0x00007ffff4153b3e in codon::ir::transform::PassManager::runAnalysis(codon::ir::Module*, std::__cxx11::basic_string<char, std::char_traits<char>, std::all
ocator<char> > const&) () from /usr/bin/../lib/codon/libcodonc.so
#4  0x00007ffff4153b3e in codon::ir::transform::PassManager::runAnalysis(codon::ir::Module*, std::__cxx11::basic_string<char, std::char_traits<char>, std::all
ocator<char> > const&) () from /usr/bin/../lib/codon/libcodonc.so
#5  0x00007ffff41537fe in codon::ir::transform::PassManager::runPass(codon::ir::Module*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocat
or<char> > const&) () from /usr/bin/../lib/codon/libcodonc.so
#6  0x00007ffff415376e in codon::ir::transform::PassManager::run(codon::ir::Module*) () from /usr/bin/../lib/codon/libcodonc.so
#7  0x00007ffff3dfe360 in codon::Compiler::compile() () from /usr/bin/../lib/codon/libcodonc.so
#8  0x000055555556e799 in ?? ()
#9  0x000055555556f67a in ?? ()
#10 0x00005555555730cb in ?? ()
#11 0x00007fffefc393fb in ?? () from /usr/lib64/libc.so.6
#12 0x00007fffefc394bb in __libc_start_main () from /usr/lib64/libc.so.6
#13 0x000055555556c775 in ?? ()
```

```
(gdb) info registers
rax            0x0                 0
rbx            0x0                 0
rcx            0x0                 0
rdx            0x0                 0
rsi            0x0                 0
rdi            0x55555f792d00      93825162358016
rbp            0x55555f7b3750      0x55555f7b3750
rsp            0x7fffffffc720      0x7fffffffc720
r8             0xd                 13
r9             0x20                32
r10            0x21                33
r11            0x455a              17754
r12            0x0                 0
r13            0x55555f792d00      93825162358016
r14            0x0                 0
r15            0x55555f7bf000      93825162539008
rip            0x7ffff40bb300      0x7ffff40bb300 <codon::ir::analyze::dataflow::RDInspector::analyze()+4928>
eflags         0x10213             [ CF AF IF RF ]
cs             0x33                51
ss             0x2b                43
ds             0x0                 0
es             0x0                 0
fs             0x0                 0
gs             0x0                 0
fs_base        0x7ffff7f59800      140737353455616
gs_base        0x0                 0
```

**Comment by inumanag** [comment]
@Miezhiko what is the content of simple.py?

**Comment by Miezhiko** [comment]
> @Miezhiko what is the content of simple.py?

print('hello world')

And it works without the release flag

**Comment by Miezhiko** [comment]
@inumanag I can still reproduce this
