### ISSUE TITLE
ImportError: /usr/local/lib/python3.12/site-packages/codon/codon_jit.cpython-312-x86_64-linux-gnu.so: undefined symbol: _ZN5codon3jit7jitInitERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

### ISSUE THREAD

**Issue by 5hojib** [exaloop/codon#592]
Here is my Dockerfile 

```Dockerfile
FROM python:3.12-slim

# Install necessary dependencies, including libstdc++ and g++ for C++11 support
RUN apt-get update \
    && apt-get install -y git curl g++ cmake llvm-13-dev libz-dev libbz2-dev \
    libboost-all-dev liblzma-dev libstdc++6 g++-10 \
    && curl -fsSL https://exaloop.io/install.sh | bash \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Add Codon to the PATH
ENV PATH="/root/.codon/bin:${PATH}"

# Set the working directory
WORKDIR /usr/src/app

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of your application code
COPY . .

# Set the command to run your start script
CMD ["bash", "start.sh"]
```

codon-jit in requirements.txt

When I try `import codon` I got this error 

```
File "/usr/local/lib/python3.12/site-packages/codon/__init__.py", line 5, in 
    from .decorator import jit, convert, execute, JITError
  File "/usr/local/lib/python3.12/site-packages/codon/decorator.py", line 17, in 
    from .codon_jit import JITWrapper, JITError, codon_library
ImportError: /usr/local/lib/python3.12/site-packages/codon/codon_jit.cpython-312-x86_64-linux-gnu.so: undefined symbol: _ZN5codon3jit7jitInitERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

**Comment by inumanag** [comment]
Duplicate of #123.

Please try `CC=clang pip install codon-jit`. I will look into better solution in the meantime.

**Comment by DamonsJ** [comment]
Traceback (most recent call last):
  File "test-codon.py", line 1, in <module>
    import codon
  File "/usr/local/lib/python3.8/dist-packages/codon/__init__.py", line 5, in <module>
    from .decorator import jit, convert, execute, JITError
  File "/usr/local/lib/python3.8/dist-packages/codon/decorator.py", line 17, in <module>
    from .codon_jit import JITWrapper, JITError, codon_library
ImportError: /usr/local/lib/python3.8/dist-packages/codon/codon_jit.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN5codon3jit7jitInitERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE


I got same error from ubuntu, python3.8

**Comment by 5hojib** [comment]
Yeah me too

**Comment by Jayanaka-98** [comment]
Same here on:

```bash
ImportError: /usr/local/python/3.12.1/lib/python3.12/site-packages/codon/codon_jit.cpython-312-x86_64-linux-gnu.so: undefined symbol: _ZN5codon3jit7jitInitERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
```

```
Python : 3.12.1
glibc : 2.31
On github codespace environment.
```

**Comment by ypfmde** [comment]
I get the same ImportError under Python 3.13 and codon v0.18.0 (on an up to date arch linux machine), no matter whether I install codon-jit via `pip install codon-jit`, or via `CC=clang pip install codon-jit` as recommended previously.

**Comment by 5hojib** [comment]
> I get the same ImportError under Python 3.13 and codon v0.18.0 (on an up to date arch linux machine), no matter whether I install codon-jit via `pip install codon-jit`, or via `CC=clang pip install codon-jit` as recommended previously.

Still I didn't find any solution, and forgot about this.

**Comment by inumanag** [comment]
Fixed in #629 [hopefully...].
