### ISSUE TITLE
pip installer on linux

### ISSUE THREAD

**Issue by vavrines** [exaloop/codon#83]
The [Python decorator part](https://docs.exaloop.io/codon/interoperability/decorator) mentions the codon library can be installed via pip install. 
The example only shows a workaround on macOS via
`python3 -m pip install codon-0.13.0-cp39-cp39-macosx_12_0_arm64.whl`
It doesn't seem to work on linux yet.
A direct `python3 -m pip install codon` throws the following error
```
ERROR: Command errored out with exit status 1:
     command: /opt/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-xek5nan9/cogent/setup.py'"'"'; __file__='"'"'/tmp/pip-install-xek5nan9/cogent/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-27df80_7
         cwd: /tmp/pip-install-xek5nan9/cogent/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-xek5nan9/cogent/setup.py", line 61
        print "Failed to build html due to ImportErrors for sphinx"
              ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Failed to build html due to ImportErrors for sphinx")?
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by layerkugou** [comment]
good idea

**Comment by inumanag** [comment]
Thanks for the report—we are aware of quite a few issues with the Python package. The new version (to be released shortly) will fix the Python package.
